name: v3.1.1 Package

on:
  push:
    branches:
      - v3.1.1

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm publish  --scope=@npkg  --access public  
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

